/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'I852318' at '6/2/16 2:54 PM' with Gradle 2.9
 *
 * @author I852318, @date 6/2/16 2:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
